name: build-extension

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
      - 'release-*'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install crx3 CLI
        run: |
          npm i -g crx3 || true

      - name: Build extension (zip + crx)
        env:
          EXTENSION_PEM: ${{ secrets.EXTENSION_PEM }}
        run: |
          bash scripts/build-extension.sh

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodeimage-extension.zip
          path: dist/nodeimage-extension.zip
          if-no-files-found: warn

      - name: Upload CRX artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodeimage-extension.crx
          path: dist/nodeimage-extension.crx
          if-no-files-found: warn


      - name: Create release on tag push and upload assets
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/nodeimage-extension.zip
            dist/nodeimage-extension.crx
