name: build-extension

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
      - 'release-*'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build extension (zip)
        run: |
          bash scripts/build-extension.sh

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-nodeimage-extension.zip
          path: dist/chrome-nodeimage-extension.zip
          if-no-files-found: warn


      - name: Create release on tag push and upload assets
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/chrome-nodeimage-extension.zip
